"DbUser" = "servian"
"DbPassword" = "shadowfox"
"DbName" = "challenge"
"DbPort" = "5432"
"DbHost" = "db-service.challenge.svc.cluster.local"
"ListenHost" = "app-service.challenge.svc.cluster.local"
"ListenPort" = "80"