apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
  namespace: jenkins
  labels:
    app: jenkins-build
    version: 1.0v
    workLoad: multi-container
spec:
  containers:
    - name: docker
      image: docker:19.03
      securityContext:
          #Not recommended - Demonstration purposes only
          allowPrivilegeEscalation: true
          runAsUser: 0
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock