apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
  labels:
    app: jenkins-build
    version: 1.0v
    workLoad: multi-container
spec:
  containers:
    - name: docker
      image: docker:19.03
      securityContext:
          #Not recommended - Demonstration purposes only
          allowPrivilegeEscalation: true
          runAsUser: 0
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      env:
      - name: JENKINS_URL
        value: http://jenkins.operations:8080
      - name: JENKINS_TUNNEL
        value: jenkins-agent.operations:50000
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      tty: trues
      env:
      - name: JENKINS_URL
        value: http://jenkins.operations:8080
      - name: JENKINS_TUNNEL
        value: jenkins-agent.operations:50000
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock