apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tech-challenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tech-challenge.selectorLabels" . | nindent 8 }}
        app: challenge-db
        version: {{ .Values.app.image.tag | default .Chart.AppVersion }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: go
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "tech-challenge.fullname" . }}-db-secrets
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}


