apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-challenge.fullname" . }}-app-secrets
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  VTT_DBUSER: {{ .Values.app.config.dbUser | default  .Values.db.config.dbUser }}
  VTT_DBPASSWORD: {{ .Values.app.config.dbPassword | default  .Values.db.config.dbPassword }}
  VTT_DBNAME: {{ .Values.app.config.dbName | default  .Values.db.config.dbName }}
  VTT_DBPORT: {{ .Values.app.config.dbPort | default  "NTQzMg==" }}
  {{- if .Values.app.config.enabled }}
  VTT_DBHOST: {{ .Values.app.config.dbHost }}
  {{- else }}
  {{- $releasefullname := include "tech-challenge.fullname" . }}
  VTT_DBHOST: {{ $releasefullname | b64enc }}LWRiLXN2Yy5zdmMuY2x1c3Rlci5sb2NhbA==s
  {{- end }}
  VTT_LISTENHOST: MC4wLjAuMA==
  VTT_LISTENPORT: ODA=