{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tech-challenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tech-challenge.selectorLabels" . | nindent 8 }}
        app: challenge-db
        version: {{ .Values.app.image.tag | toString }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgress
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | toString }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "tech-challenge.fullname" . }}-db-secrets
          ports:
          - containerPort: 5432
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- if .Values.db.persistData.enabled }}
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
            subPath: postgres
          {{- end }}
      {{- if .Values.db.persistData.enabled }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "tech-challenge.fullname" . }}-pvc
      {{- end }} 
{{- end}}

