#DB configs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db-secrets
type: Opaque
data:
  POSTGRES_DB:  {{ .Values.db.config.dbName | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.db.config.dbPassword | b64enc}}
  POSTGRES_USER: {{ .Values.db.config.dbUser | b64enc}}
