apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db-seed
spec:
  template:
    spec:
      containers:
      - name: app
        image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/sh"]
        args: ["-c", "echo 'Sleep time initiated - waiting on db to install'; sleep {{.Values.jobs.sleep}}; ./TechChallengeApp updatedb"]
      restartPolicy: Never
  backoffLimit: 4
