{{- if .Values.jobs.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db-seed
spec:
  template:
    spec:
      containers:
      - name: app
        image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag | toString }}"
        envFrom:
        - secretRef:
            name: {{ include "tech-challenge.fullname" . }}-app-config
        command: ["/bin/sh"]
        args: ["-c", "echo 'Sleep time initiated - waiting on db to install'; sleep {{ .Values.jobs.sleep }}; ./TechChallengeApp updatedb"]
      restartPolicy: Never
  backoffLimit: 4
{{- end}}
