---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-challenge.fullname" . }}-app-svc
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "tech-challenge.selectorLabels" . | nindent 4 }}
    app: challenge-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-challenge.fullname" . }}-db-svc
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    {{- include "tech-challenge.selectorLabels" . | nindent 4 }}
    app: challenge-app
---
{{- if .Values.nodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-challenge.fullname" . }}-app-nodeport
  labels:
    {{- include "tech-challenge.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: {{ .Values.nodePort.port }}
  selector:
    {{- include "tech-challenge.selectorLabels" . | nindent 4 }}
    app: challenge-app
  {{- end }}