---
#DB configs
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DB: Y2hhbGxlbmdl
  POSTGRES_PASSWORD: c2hhZG93Zm94
  POSTGRES_USER: c2Vydmlhbg==
  PG_DATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL2RiLWZpbGVzLwo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-db
  labels:
    app: challenge-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-db
  template:
    metadata:
      labels:
        app: challenge-db
        version: 1.0v
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
        - secretRef:
            name: db-secrets
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
            subPath: postgres
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"  
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: db-pvc-4

