---
#DB Service
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: challenge
spec:
  selector:
    app: challenge-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
#APP ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: challenge
spec:
  selector:
    app: challenge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
#APP NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: app-service-public
  namespace: challenge
spec:
  type: NodePort
  selector:
    app: challenge-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080