apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
  namespace: challenge
spec:
  template:
    spec:
      containers:
      - name: app
        image: krishees/techchallengeapp
        command: ["/bin/sh"]
        args: ["-c", "echo 'Sleep time initiated - waiting on db to install'; sleep 180; ./TechChallengeApp updatedb"]
      restartPolicy: Never
  backoffLimit: 4
